brew "coreutils"
brew "git"
brew "rbenv"
brew "thefuck"
brew "zsh"

tap "homebrew/cask"
cask "altair-graphql-client"
cask "google-chrome"
cask "iterm2"
cask "Spectacle"
cask "Spotify"
cask "sublime-text"
